In [67]:
#################################
# Author : Sanjeev 
# Date of creation : 14.04.2022
#################################

# **PyTorch Basics**

### **This notebook contains basics pytorch operation that will be used for implementing deeep learning models using pytorch framework**

#### ***Reference***: I have followed the [Deep-Lizard](https://deeplizard.com/learn/video/MasG7tZj-hw) to learn all these concepts.

In [1]:
'''importing libararies'''
import torch
import numpy as np

#### **creating tensor from data**


1.   torch.Tensor(data) 
2.   torch.tensor(data) 
3.   torch.as_tensor(data) 
4.   torch.from_numpy(data)

---



---



In [9]:
# data
data = np.array([1,2,3])

# tensor created using class contructor of pytorch
t1 = torch.Tensor(data) # float output

# tensor created using factory function of pytorch
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [11]:
print(t1) # float output
print(t2) # int output
print(t3) # int output
print(t4) # int output

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [12]:
print(t1.dtype) # float output
print(t2.dtype) # int output
print(t3.dtype) # int output
print(t4.dtype) # int output

torch.float32
torch.int64
torch.int64
torch.int64


### **Memory: sharing vs copying concept**
---



####   **not sharing the memory**
 * changing the value of data will not impact the tensor created from the same data*
   *   torch.Tensor(data)
   *   torch.tensor(data)    

####  **sharing the memory location**
* tensor values will be modified by changing the the data values
    * torch.as_tensor(data)
    * torch.from_numpy(data)
---

In [16]:
# execution

# data
data = np.array([1,2,3])

# not sharing memory
t1 = torch.Tensor(data) 
t2 = torch.tensor(data)

# memory shared
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

'''changing the data values of the numpy array'''

data[0] = 1
data[1] = 1
data[2] = 1

In [17]:
print(t1) # will not impacted by changing data values
print(t2) # will not impacted by changing data values

print(t3) # modified by changing data values
print(t4) # modified by changing data values

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 1, 1])
tensor([1, 1, 1])


### **Inference:** 
#### which one to prefer in daily use
---
**torch.tensor()**


*  if copying of data is needed
  * as it provide freedom to select the dype of tensor

**torch.as_tensor()**
* if memory sharing is needed
---


# **TENSOR OPERATIONS**


*   reshaping operations
*   element wise operations
*   reducation operations
*   access operations

In [18]:
# reshaping operation
t = torch.tensor([[1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3],
                  [4,4,4,4]], dtype=torch.float32)

In [19]:
t.shape

torch.Size([4, 4])

In [21]:
t.numel() # no of elements in the tensor

16

In [22]:
t.reshape(2,8).shape # reshaping the tensor

torch.Size([2, 8])

**squeeze operation**


*   remove an axis that has length equal to 1



In [23]:
t.reshape(1,1,16).squeeze().shape

torch.Size([16])

**unsqueeze operation**
*   add the new axis at the mentioned dim position

In [24]:
t.reshape(1,16).unsqueeze(dim=2).shape # added the new dim at index = 2

torch.Size([1, 16, 1])

## **concat vs stack**
 
* **concat:** concat operation will be performed at already exiting dimensions
* **stack:** stack operation introduced the new axis

In [25]:
# these tensors will represent 3 images of a batch
t1 = torch.tensor([[1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1],
                   [1,1,1,1]])

t2 = torch.tensor([[2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2],
                   [2,2,2,2]])

t3 = torch.tensor([[3,3,3,3],
                   [3,3,3,3],
                   [3,3,3,3],
                   [3,3,3,3]])

print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])


In [26]:
# using the stack operation create the batch of 3 images
batch = torch.stack([t1,t2,t3], dim=0)
batch.shape

torch.Size([3, 4, 4])

In [27]:
# add the color channels to the batch of images
batch = batch.unsqueeze(dim=1)
batch.shape

torch.Size([3, 1, 4, 4])

In [28]:
'''how to intepret the result'''
batch[0] # give the first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [29]:
batch[0][0] # first image first color channel

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [30]:
batch[0][0][0] # first row of the color channel of first image

tensor([1, 1, 1, 1])

In [31]:
batch[0][0][0][0] # first pixel value of first color channel of first image

tensor(1)

**flattening operation using custom function**

In [32]:
def flatten(t):
  t = t.reshape(1,-1) # -1 means it will automatically calc this dim value
  t.squeeze()

  return t

In [33]:
# pytorch also provide inbuilt flatten operation
batch.flatten(start_dim=1).shape

torch.Size([3, 16])

## **Broadcasting and elementwise operation**

In [35]:
t1 = torch.tensor([[1,2],
                   [3,4]], dtype=torch.float32)

t2 = torch.tensor([[9,8],
                   [7,6]], dtype = torch.float32)

# element wise addition 
t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [37]:
# concept of broadcasting
''' t1 + torch.tensor(np.broadcast_to(2,t1.shape), dtype=t1.dtype)'''
t1 +2    

tensor([[3., 4.],
        [5., 6.]])

In [38]:
'''more example'''
t1 = torch.tensor([[1,1],
                   [1,1]], dtype=torch.float32)

t2 = torch.tensor([[2,4]], dtype=torch.float32)

In [39]:
t1 + t2  # before addition broadcasting operation done at the background

tensor([[3., 5.],
        [3., 5.]])

In [40]:
'''using broadcasting '''
t1 + np.broadcast_to(t2.numpy(), t1.shape)

tensor([[3., 5.],
        [3., 5.]])

## **reducation operation**

In [54]:
# tensor creation
t = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype=torch.float32)

In [55]:
t.sum() # sum of all elements of tensor

tensor(45.)

In [56]:
t.numel() # number of elements of tensor

9

In [57]:
t.prod() # product of tensor elements

tensor(362880.)

In [58]:
'''reducation operation in particular axis'''
t.sum(dim=0)  # sum along rows --> means rows has been added

tensor([12., 15., 18.])

In [59]:
t.sum(dim=1) # sum along the columns ---> means columns has been added

tensor([ 6., 15., 24.])

In [60]:
'''
argmax operation: will return the max val index position
   # if axis is not specified, it will return the max value index position when tensor is flattened
'''
t.argmax()

tensor(8)

**mean**

In [62]:
t.mean(dim= 0) # mean along row

tensor([4., 5., 6.])

In [63]:
t.mean(dim = 1) # mean along col

tensor([2., 5., 8.])

In [64]:
'''
how to get the numerical values of the tensor
t.item() ---> if there is single element
t.to_list() ---> if there is multiple elements
'''

t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]